### ISSUE TITLE
Add AUTHENTICATION_HEADER to settings.py example in wiki

### ISSUE THREAD

**Issue by nbently** [usnistgov/NEMO#118]
I'd like to propose that the setting for `AUTHENTICATION_HEADER` be added to the settings.py example in the wiki.

I beat myself up over why `REMOTE_USER` auth wasn't working for the better part of 6 hours before I figured out this existed lol.

**Comment by nbently** [comment]
Thanks @rptmat57!

**Comment by rptmat57** [comment]
np. if you have any issues in the future you can always check out
https://groups.google.com/a/list.nist.gov/d/forum/nemo
