### ISSUE TITLE
Issue regarding setup and initialization 

### ISSUE THREAD

**Issue by KyleJHUAPL** [usnistgov/NEMO#15]
After following the installation guide step for step, on three different operating systems, I cannot get any function out of NEMO. When attempting to access the web page, even locally (localhost:8000), I am greeted by a timed out error. There is no error access logging, aside from when attempting to access it via a host not specified in allowed hosts. I have no issue getting the splash_pad image to function. 

Some more information:
This has been tried using Ubuntu 18.04 LTS, Rhel 7, and Mojave 10.14.6.
Additionally, I tried using version 1.20.0, instead of the most recent release, but had the same issue.

**Comment by mrampant-nist** [comment]
try using `ALLOWED_HOSTS = ['*']` in your settings.
also, you will need an external way to authenticate to NEMO (via your own LDAP for example)

**Comment by mrampant-nist** [comment]
The installation guide is geared towards production systems and require a bit more experience with NEMO and Nginx.

Take a look at the [Quick Start](https://github.com/usnistgov/NEMO/wiki/NEMO-with-docker-Quick-Start) which will provide a pre-made configuration and Nginx.

or follow the [dev setup](https://github.com/usnistgov/NEMO/wiki/Development-Setup) steps to run  NEMO locally without docker

**Comment by KyleJHUAPL** [comment]
After reviewing the Quick Start and dev setup, as per your recommendation, I've managed to get basic functionality out of nemo. I've been attempting to modify the Quick Start configuration, to get a better grasp on NEMO's configurations. 
However, I'm still having issues hooking LDAPS up to NEMO. 

When a user has not been added to the NEMO database in any way, it spits out

`nemo     | 01-09 19:35:51 [09/Jan/2020 14:35:51] django.request WARNING Username Example attempted to authenticate with LDAP, but that username does not exist in the NEMO database. The user was denied access.
nemo     | 01-09 19:35:51 Username Example attempted to authenticate with LDAP, but that username does not exist in the NEMO database. The user was denied access.`

However, if you add the individual to the database (Via the django createsuperuser command).

`nemo     | 01-09 18:45:56 ERROR:root:invalid CA public key file
nemo     | 01-09 18:45:56 Traceback (most recent call last):
nemo     | 01-09 18:45:56   File "/usr/local/lib/python3.6/site-packages/NEMO/views/authentication.py", line 94, in authenticate
nemo     | 01-09 18:45:56     t = Tls(validate=CERT_REQUIRED, version=PROTOCOL_TLSv1_2, ca_certs_file=server['certificate'])
nemo     | 01-09 18:45:56   File "/usr/local/lib/python3.6/site-packages/ldap3/core/tls.py", line 93, in __init__
nemo     | 01-09 18:45:56     raise LDAPSSLConfigurationError('invalid CA public key file')
nemo     | 01-09 18:45:56 ldap3.core.exceptions.LDAPSSLConfigurationError: invalid CA public key file`

The CA cert is currently in nemo/secrets, and pointed to in the nemo/settings.py file. I've already tested this cert prior, and it had no issues with authentication.
I'm not sure where the locations referenced in the error are, I'm assuming they're in the docker container. (Does that need to be hand-modified for this?)

**Comment by mrampant-nist** [comment]
about authentication and LDAPS, first of all, you only need one superuser to get in to NEMO originally (using the same username as in your ldap) then login in as that user you can create "regular" users in the Administration part of NEMO.

also, you can test your ldap configuration by running `python NEMO/provisioning.py test_ldap_authentication` and entering your details.

lastly, the certificate NEMO expects should be in PEM ASCII format. you should be able to open your certificate file with a text editor and confirms it starts with `---- BEGIN CERTIFICATE----` and ends with `----END CERTIFICATE----`
if your certificate is not in PEM, there are tools and command line options to do it.
see [this question on serverfault](https://serverfault.com/questions/254627/how-do-i-convert-a-cer-certificate-to-pem)

I hope this helps

**Comment by mrampant-nist** [comment]
can I close this or are you still having issues?
