### ISSUE TITLE
Feedback and Safety emails fail to deliver if SMTP server does not allow sender spoofing

### ISSUE THREAD

**Issue by r-xyz** [usnistgov/NEMO#150]
After reviewing email configuration, we are experiencing the following error when a user reports a Feedback or Safety Issue.
```
NEMO.utilities ERROR {'safety_or_feedback_email': (553, b'5.7.1 <user_email>: Sender address rejected: not owned by user SMTP USER')}

Traceback (most recent call last):
  None
```
Despite the missing traceback, we can confirm the error is due to the SMTP server rejecting any attempt to send email from an email address not associated with the SMTP user/credentials (Security measure).

Would it be possible (and would it make sense) to send the email from `user office` email, and add the user email in TO/CC? The recipients will always be able to reply to the user directly using `Reply-All`; alternatively (less practical) the user name/email could be shown in the email. Also, the users will have track record of the message submitted.

I can help with the PR if needed, still I guess it would require a small change in `Email Logs` to keep track of from which user the event originated (otherwise all Feedback/Issue email will only show `user office` as Sender).

EDIT: I am not sure if there are also other email types which might be sent on behalf of a user. Same issue would apply there.

**Comment by rptmat57** [comment]
Hi,
If your SMTP does not allow sender spoofing, you can use the following email settings in `settings.py`:

```
DEFAULT_FROM_EMAIL = "NEMO Webmaster <webmaster@mydomain.com>"
# Change this to True to ALWAYS use DEFAULT_FROM_EMAIL as sender for all emails and use REPLY_TO with the original sender
# Useful when using a single email address (gmail) that prevents "spoofing" (sending as someone else)
EMAIL_USE_DEFAULT_AND_REPLY_TO = False
```

**Comment by r-xyz** [comment]
Hi Mathieu,
Thanks, I missed the updates to the wiki [Settings page](https://github.com/usnistgov/NEMO/wiki/Settings) (actually not only regarding this setting).
A proposal: would it be possible to add a copy of the settings template somewhere (e.g. resources directory) in the source, so it could be easier to check changes when a new version is released? The wiki could then link directly to the latest version.
Thanks

**Comment by rptmat57** [comment]
Great idea. done!
