### ISSUE TITLE
production NEMO deployment without  external authentication server

### ISSUE THREAD

**Issue by sbonaime** [usnistgov/NEMO#16]
Hi,

I would like to use NEMO in production without  external authentication server. Is there an easy way to do it like on the docker image ?

Thank you

**Comment by dsbarth** [comment]
Hi Sebastien,
At Princeton, we are running this with local DB based authentication. You can see the code in my branch, and I'm happy to talk it over with you.
-David

**Comment by mrampant-nist** [comment]
Salut Sebastien,
Your best bet is to customize NEMO's code or use the Princeton Branch. You will have to build your own docker image and maintain/update it yourself.
Their is no easy way to do this directly with the docker image as is.

However, there are docker images for ldap servers and you could also try something like [KeyCloak](https://www.keycloak.org/) from RedHat.
It would then be very easy to connect the 2.

Hésites pas si tu as d'autres questions

**Comment by sbonaime** [comment]
I worked to use our own internal LDAP for the authentification. But I had to modify few lines of NEMO/views/authentication.py because our LDAP is a little special.

I saw on the docker documentation that "A decoupled "REMOTE_USER" method" and "# NEMO can integrate with a custom Identity Service to manage user accounts on
# related computer systems, which streamlines user onboarding and offboarding."

Can I use those options to add my "custom LDAP authentication" without having to build my docker image ?

````
# There are two options to authenticate users:
#   1) A decoupled "REMOTE_USER" method (such as Kerberos authentication from a reverse proxy)
#   2) LDAP authentication from NEMO itself
AUTHENTICATION_BACKENDS = ['NEMO.views.authentication.LDAPAuthenticationBackend']

# Specify your list of LDAP authentication servers only if you choose to use LDAP authentication
LDAP_SERVERS = [
	{
		'url': 'ldap.another.org',
		'domain': 'ANOTHER',
		'certificate': '/nemo/secrets/root.crt',
	}
]

# NEMO can integrate with a custom Identity Service to manage user accounts on
# related computer systems, which streamlines user onboarding and offboarding.
IDENTITY_SERVICE = {
	'available': False,
	'url': 'https://identity.example.org/',
	'domains': ['EXAMPLE', 'ANOTHER'],
}
````

**Comment by mrampant-nist** [comment]
Hi,
what are you custom changes? if it's something that would make sense to have configurable I would be willing to make that change in NEMO.
To build your docker image from your code, all you have to do is to run `docker build --tag my_nemo .` from the root directory where NEMO's code is, and that will build you a docker image with the image name "my_nemo"

**Comment by sbonaime** [comment]
Our LDAP is kind of specific. I don't think it is usefull to create an option for that. 
I made some modification in NEMO/views/authentication.py and I can now login :-)

Thank you
