### ISSUE TITLE
[Feature request] Send new task notifications to users with reservations on that tool

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#166]
Feature request:
It would be wonderful if when a new task is created on tool X, that task notification is also sent to all users who currently have tool X reserved to notify them that the tool may be down, or their process my otherwise be impacted.

Optional extension 1 -- If a user has used tool X within the last N days (say, N=7 if it can't be conveniently configurable), notify them of the new task as well.  This is useful on the assumption that if a user recently used tool X, they are likely to want to use tool X again in the near future and may want to know to track its status.  Whether or not to receive these updates for recently used tools could be a user preference (checkbox).

Optional extension 2 -- If a user opts in (another user pref checkbox) and was in the group who received the new task notification, also send them all updates and resolution associated with that task.

I don't see a case where users need to be notified of a task that started well before they used the tool.  In that case, they would have already seen the task and reviewed the history when they created their reservation or reserved the tool.

I am specifically targeting users (like myself) who want to receive in their inbox any and all news about the tool in their critical path getting fixed.  Many of our users have other projects/activities and may not be checking NEMO daily to check status updates, so they appreciate updates by email, but we don't want to burden our staff to provide these updates.

**Comment by rptmat57** [comment]
in the next version v6.0.0 any user will have the ability to subscribe to tool notification in their preferences (as long as the setting is turned on in customizations). They do have to be qualified on that tool though.

I believe this should take care of this functionality, for the most part. The main difference is that it does require user action and is not automatic. Feel free to reopen if you believe it is not sufficient

**Comment by massey21** [comment]
This works.  Thank you!

**Comment by rptmat57** [comment]
I just wanted to add that if there is a problem with a tool, the reservation reminder warning email is already sent to users with upcoming reservations.
