### ISSUE TITLE
Superusers receive task/problem reports and updates

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#173]
Can the option for superusers to receive task/problem reports be added?  I understand this may not be desirable in every context, so a global boolean to control this behavior might be reasonable.  Thanks for considering this.

Or if this feature already exists, how do I enable it?  Unless I misunderstood, your 8/8 email suggested that superusers should receive alerts and maintenance updates.

**Comment by rptmat57** [comment]
Sounds reasonable. It'll be in NEMO 5.1.0
