### ISSUE TITLE
[Feature request] See summary of requested configurations on calendar view

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#177]
Hi, users are requesting the ability to see a short version of the configurations requested by other users on the tool reservation calendar.  This is driven by users needing to coordinate their sputter target requests with other users at the time of reservation to minimize burden on staff -- so they would want to see the requested targets in the empty space on these blue boxes rather than having to click in.  When there are 10+ reservations over a few days, this would make it much easier to see at a glance what the upcoming needs are so users can trade reservations if it eliminates the need for an additional target change.

![image](https://github.com/usnistgov/NEMO/assets/98626874/626d5246-b2da-4132-a8c2-d2a1422c61e7)

I can see cases where this might not make sense for every tool -- some configurations might be too analog or verbose to display reasonably.  So, this could be a checkbox toggle option to "display config request on calendar" at the bottom of the Detailed Admin --> Configurations page (off by default).

This is the information that would be helpful to display:
![image](https://github.com/usnistgov/NEMO/assets/98626874/ae3d2edc-b3f4-4d35-9456-1eef15641dca)

**Comment by rptmat57** [comment]
this was added to NEMO 5.1.0
