### ISSUE TITLE
Enhancements !

### ISSUE THREAD

**Issue by sbonaime** [usnistgov/NEMO#18]
Hi,

I am using NEMO for few minutes now. It it exactly what I am looking ! 

However, I can see few useful enhancement :

- option to duplicate a tool
- modify a News in the "website" and not in the backend interface
- modify a reservation
- picture(s) for each tool
- comments for each tool
- files related to the tool like manuals or documentation

Thank you

**Comment by mrampant-nist** [comment]
Hi,
Do you mind posting this on the [NEMO Forum](https://groups.google.com/a/list.nist.gov/d/forum/nemo) instead? since it's not really an issue and you might get some feedback from others.
I will go ahead and close this
