### ISSUE TITLE
[Feature req] Users subscribe to tool notifications

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#188]
Some users would like the option to subscribe to notifications -- receive tool problem/update/resolution emails.  Could this user prefs feature be accessible to all users, not just staff? 

![image](https://github.com/usnistgov/NEMO/assets/98626874/21463bae-8f74-4211-be18-54a60532b8b5)

The task status is visible to users already, so I can't think of a downside to making available the option to receive these notifications via email.

**Comment by massey21** [comment]
Bumping this request.  More users (and PIs) are requesting it.

**Comment by rptmat57** [comment]
this will be available in the next release
