### ISSUE TITLE
[Feature req] Attach files and include hyperlinks in broadcast emails

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#189]
It would be wonderful if the email broadcast could support hyperlinks or attachments!  

Currently our only option, to my knowledge) is to paste the a raw URL to the page or file we want to distribute to users.

![image](https://github.com/usnistgov/NEMO/assets/98626874/8e3d81c1-1db4-4dbf-be25-b5c30ad7c69f)

**Comment by rptmat57** [comment]
Good news, this is already available. Attachments were added in 4.7.0
https://nemo-demo.atlantislabs.io/compose_email/?audience=user&no_type=on&selection=1&selection=2&selection=3&selection=4
