### ISSUE TITLE
[feature request] Status dashboard tools link to tool page

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#191]
Hi, can the tools listed on the status dashboard (especially problematic tools) link directly to the corresponding tool page?  This is driven by wanting to see _what_ the problem is with each tool once we see at a glance that it's down.  Currently it pops up the information displayed on a tool's details tab.

![image](https://github.com/usnistgov/NEMO/assets/98626874/93f5d3ff-1b76-4619-9f6f-2bcfdca452dd)

[this is part 1... part 2 is a closely related but separate feature request that will go in another ticket]

**Comment by rptmat57** [comment]
I propose making the name of the tool in the popup the link to the tool control page. would that work?
<img width="212" alt="image" src="https://github.com/usnistgov/NEMO/assets/14329388/8d425940-2f23-455e-85bb-98220e2ed89d">

**Comment by massey21** [comment]
That would work!  Thanks.
