### ISSUE TITLE
[feature request] links to tool pages

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#193]
Is it possible to link directly to tool pages, and even specific tabs within those tool pages?  

For example:
https://nemo.[domain].[tld]/tool_control/[mytoolname]#details

This would facilitate not only some of my previous requests, but it would also allow us, for instance, to create a tool called "Facility Forms" (with documents attached) and link to it directly from the front-page dashboard -- without having to create a nonstandard HTML page to house links to our internal facility-specific documents/forms.

Thanks for your consideration, and bearing with my endless flood of feature requests.  I know it's a lot.

**Comment by rptmat57** [comment]
You can already link to tool control (but not tabs):
https://nemo-demo.atlantislabs.io/tool_control/1/
https://nemo-demo.atlantislabs.io/tool_control/2/

Otherwise, for general documents/forms, some facilities are using the Safety link for that, and creating a special category of documents there. Just an idea

**Comment by massey21** [comment]
This is great!  I didn't know I could append the tool ID number.  This serves my needs for the time being -- I set up a "forms-and-docs" tool and can attach documents, and it would be conceptually trivial to expand this to a tool category of multiple document-related "tools" if/when it's needed.

More broadly I think that a document area in NEMO would still be beneficial, but given the available workarounds I concede that it's low priority.

**Comment by rptmat57** [comment]
I guess with the new version you could also change the main menu item to "Documents & Safety" or something like that and use the safety items as facility documents.
We could probably make the safety section more versatile so it can be used for general documentation
