### ISSUE TITLE
[feature request] visibility of qualified users on tools

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#201]
Following from email discussion -- It would be helpful for superusers (at a minimum) to be able to see who is qualified on their tools.  More broadly, it might be helpful for _users_ to see who else is qualified.

This would be viewable on the tool details page.

While superusers seeing qualified users on their tools seems like it ought to be a default behavior, I could imagine customization toggles for both enabling superusers to see qualified users on their tools and enabling all users to see who is qualified.

Thanks for all the ongoing support and development!

**Comment by rptmat57** [comment]
will be available in 5.3.0: superusers by default and customization setting for allowing anyone to see the list
