### ISSUE TITLE
Custom Time Format not working in Calendar events

### ISSUE THREAD

**Issue by r-xyz** [usnistgov/NEMO#210]
Hello,
I wanted to file in a minor bug.

When specifying a different time format (e.g. 24h), both under `settings.py` and under Calendar Customizations, the events are still shown in 12h format in the calendar (1:15-2:00 vs the left axis in example below).
Maybe we need to add [`timeFormat`](https://fullcalendar.io/docs/v3/timeFormat) somewhere in [NEMO/templates/calendar/calendar.html](https://github.com/usnistgov/NEMO/blob/master/NEMO/templates/calendar/calendar.html)?
Thanks in advance

![image](https://github.com/usnistgov/NEMO/assets/100710244/f9d3f635-4bba-4fd7-971a-2f8b0d8764ba) 
![image](https://github.com/usnistgov/NEMO/assets/100710244/5ed3a4bd-2b1e-4de7-886e-4ae4b990f0ea)

**Comment by rptmat57** [comment]
Right, that option is not currently supported in NEMO.

It should be pretty straightforward, just need to add `timeFormat` to either the global calendar options, or have one for each view (day, week, month) if we want better flexibility. I would go with the latter.

They should go right next to the `columnFormat` properties

**Comment by r-xyz** [comment]
Thanks for the insight.
Working on it.
I am just wondering: would it make sense to reuse the same settings as [`reservation_confirmation_time_format`](https://github.com/usnistgov/NEMO/blob/f89c983f97cb2bf0a21d7a3681340cb871347e77/NEMO/views/customization.py#L275)? (Maybe renaming it to `reservation_time_format/calendar_reservation_time_format` and moving it outside of the "reservations confirmations" section in Configuration)
It might also be more straightforward to make it `calendar_time_format`, if we previously refactor the current [`calendar_time_format`](https://github.com/usnistgov/NEMO/blob/f89c983f97cb2bf0a21d7a3681340cb871347e77/NEMO/views/customization.py#L259) to something like `calendar_slot_time_format` or `calendar_axis_time_format` (since it is only applied to axis ticks/slots).

**Comment by abuckles-uci** [comment]
@r-xyz I worked on the reservation confirmation feature. In my opinion, they should stay separate variables. The reservation confirmation is more suited towards a longer form date format, while the calendar might not be. @rptmat57 has the final say of course though.

**Comment by r-xyz** [comment]
@abuckles-uci thanks for the useful feedback and the even more for the new feature (using it already).
I was thinking about the time format only -not the date- since I expected less variability in format and it might keep the change smaller.
Nonetheless you are right: I was thinking mainly 24h, whereas in 12h format you might still want differences depending on the view. I had not noticed that the current format slightly changes between day/week and monthly view.
I think I would add three different options, as indeed @rptmat57 initially suggested.
I would still suggest to rename `calendar_time_format` as well as clarify its  usage on customization. I will submit a PR soon.

**Comment by rptmat57** [comment]
that makes sense. let's add the 3 options and rename `calendar_time_format`
thanks!
