### ISSUE TITLE
Datetimepicker do not follow 'First day of the week' Calendar Customization

### ISSUE THREAD

**Issue by r-xyz** [usnistgov/NEMO#231]
NEMO has built-in functionality to select first day of week.
<img src="https://github.com/usnistgov/NEMO/assets/100710244/86687a97-7e3b-44a6-823d-3676812f8d98" height="150">

This apply correctly to weekly/monthly Calendar views:
<img src="https://github.com/usnistgov/NEMO/assets/100710244/34118b7c-7a04-437d-9d35-06f85baffb7d" width="600">

Unfortunately, the same setting is not consistently implemented in datetimepicker.

<img src="https://github.com/usnistgov/NEMO/assets/100710244/3195386a-a0df-4e57-87ad-a12e19971e3f">

Current datetimepicker do not implement any `weekStart` option, but if you have any suggestions on how to implement it, I can submit a PR.

**Comment by rptmat57** [comment]
there is a way, or at least something to start thinking about:

```
moment.updateLocale('en', {
  week: { dow: 1 } // Monday is the first day of the week
});
```

now, it has to be done before creating the pickers, so ideally it would be placed in the `base.html` template, at the top right after loading moment.js.

Or even better, at the top of `nemo.js`. that might be easier and faster.

Now, I don't believe moment.js automatically sets the locale, so this should work for everyone regardless of their browser/computer's locale.
