### ISSUE TITLE
Usage page errors when no month is chosen

### ISSUE THREAD

**Issue by Valilian** [usnistgov/NEMO#235]
Hi @rptmat57, 
We ran across an error where if a user chooses the blank month option and has no custom dates chosen it will show as "Invalid Date" 
![image](https://github.com/usnistgov/NEMO/assets/9422681/e5cd8ca2-8dfa-4b20-abd8-8965b6dce5e9)
and if they click on the update button while the dates are like this it will throw an incorrect format error. like this:
![image](https://github.com/usnistgov/NEMO/assets/9422681/62ad9076-cda0-425f-94c4-5d9bd34cdf15)

To fix this issue when users input this invalid date should we instead catch this error and give back the current month's usage?

**Comment by rptmat57** [comment]
Thanks for reporting that!
I've seen this same error message a few times, but never knew where it came from.
This will be fixed in 6.0.0
