### ISSUE TITLE
Issue with updating tool when a tool image has been uploaded

### ISSUE THREAD

**Issue by dsbarth** [usnistgov/NEMO#24]
I'm having some trouble with the new tool image feature. I am able to upload a tool image, which works as expected. After that, if I want to clear the image or add a new image, this also works fine. However, when I want to make any changes to the tool that are unrelated to the image, I get a FileNotFoundError for the image. I suspect the issue is in the pre-save receiver on editing the tool, but I tried a few changes and still could not get it to work. Removing the pre-save entirely resulted in a copy of the image being saved every time any change was made in the tool admin form (even if the change had nothing to do with the image).

**Comment by mrampant-nist** [comment]
I just tried locally and had no issues. I was able to save with image, clear, add another one, and change other fields, and it all worked.

1. are you using a docker image or runserver locally?

2. do you have the stack trace?

3. which line are you getting the FileNotFoundError at?

4. also, can you try adding a try except block in the presave to catch any exceptions to see if making other changes are working?

**Comment by dsbarth** [comment]
Hi Mathieu, thanks for your help and for the quick response. I actually just found a solution a minute ago, by removing the presave entirely and adding an app called django_cleanup to handle it. I still don't know why it didn't work for me before, or why I'm getting different results than you are.

1. I'm using a docker image (which I build and run locally)

2. Stack trace here:
Traceback:

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in wrapper
  606.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in change_view
  1648.         return self.changeform_view(request, object_id, form_url, extra_context)

File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  45.         return bound_method(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in changeform_view
  1529.             return self._changeform_view(request, object_id, form_url, extra_context)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in _changeform_view
  1572.                 self.save_model(request, new_object, form, not add)

File "/usr/local/lib/python3.6/site-packages/NEMO/admin.py" in save_model
  162. 			record_remote_many_to_many_changes_and_save(request, obj, form, change, 'qualified_users', super(ToolAdmin, self).save_model)

File "/usr/local/lib/python3.6/site-packages/NEMO/models.py" in record_remote_many_to_many_changes_and_save
  1777. 	save_function_pointer(request, obj, form, change)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in save_model
  1088.         obj.save()

File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py" in save
  741.                        force_update=force_update, update_fields=update_fields)

File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py" in save_base
  779.                 force_update, using, update_fields,

File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py" in _save_table
  848.                       for f in non_pks]

File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py" in <listcomp>
  848.                       for f in non_pks]

File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/files.py" in pre_save
  288.             file.save(file.name, file.file, save=False)

File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/files.py" in save
  87.         self.name = self.storage.save(name, content, max_length=self.field.max_length)

File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py" in save
  52.         return self._save(name, content)

File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py" in _save
  266.                     fd = os.open(full_path, self.OS_OPEN_FLAGS, 0o666)

Exception Type: FileNotFoundError at /admin/NEMO/tool/16/change/
Exception Value: [Errno 2] No such file or directory: '/nemo/media/tool_images/angstrom-metals-sputterer.png'

3. My line numbers don't exactly match up with yours, but it seems like the error occurs when the model is saved in the admin form.

4. Putting a try except block around the whole pre-save didn't seem to change the trace at all.

**Comment by mrampant-nist** [comment]
would you mind testing it with the latest official NEMO image (nanofab/nemo:2.1.0) or with the splash_pad (nanofab/nemo_splash_pad)
I tried with the splash pad and cannot replicate. I am trying to find out if this is due to some of your custom changes or a bug in our code.

**Comment by dsbarth** [comment]
I could not replicate with the splash_pad. Unfortunately, I don't think I will be able to get the official image working in my setup without some significant changes, at which point it might not be meaningful anymore. I cannot find any part of the code that I think is relevant to this that I have changed at all, so I'm still pretty confused.

**Comment by mrampant-nist** [comment]
I am confused too.
I guess it could also have something to do with your settings, if you are using any kind of storage other than the default for media: (property "DEFAULT_FILE_STORAGE")
or depending on what volumes you are mounting to your media folder with docker and what permissions are on those folders

**Comment by dsbarth** [comment]
I could not reproduce the issue when running the splashpad using my code. I did not change any defaults for media storage in my settings. I think you are probably right that it might be related to the volumes, though I still don't see how. I believe my volumes are set up exactly as recommended. One difference is that I'm running Docker for Windows, so I guess that means there is an additional layer of virtualization. My volume mount looks like this, and I haven't had any other issues with it: --volume <path on host>/nemo:/nemo

Also, I can see the image files showing up and being deleted in my volume pretty much as you'd expect.

**Comment by mrampant-nist** [comment]
I just tested on windows, and got an error as NEMO was trying to delete the image when I didn't change it (but changed another field). For me it was a permission error, but if I didn't have the permission error it would have deleted the file which it shouldn't have done.
It would have probably given me a FileNotFound like you had.
I will look into why on windows it thinks the file is changed when it's not and try to fix the issue.

thanks for all the information, I am glad I am able to reproduce it now.

**Comment by mrampant-nist** [comment]
Fixed the issue. please update and double check it's not happening anymore (reopen if necessary).
thanks for reporting this bug, the code was actually resizing images every time and trying to delete and resave them

**Comment by dsbarth** [comment]
This solved it. Images are working as expected now. Thanks!
