### ISSUE TITLE
install NEMO on a CentOS server: installation instructions: ambiguity

### ISSUE THREAD

**Issue by dadhogy** [usnistgov/NEMO#3]
in the installation instructions it says "Reference this file in your settings.py". It does not, however, say how this is to be accomplished. At this point in the installation there is no "settings.py" file. What am I missing?

**Comment by saltlakeryan** [comment]
I used the development settings here (not for production):
https://github.com/usnistgov/NEMO/wiki/Development-&-test-settings.py

**Comment by dadhogy** [comment]
Thanks! Duh, dunno how I missed this.
    --Mike
    
    
    On 1/16/18 3:24 PM, saltlakeryan wrote:
    
    
      I used the development settings here (not for production):
        https://github.com/usnistgov/NEMO/wiki/Development-&-test-settings.py
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/usnistgov/NEMO","title":"usnistgov/NEMO","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/usnistgov/NEMO"}},"updates":{"snippets":[{"icon":"PERSON","message":"@saltlakeryan in #3: I used the development settings here (not for production):\r\nhttps://github.com/usnistgov/NEMO/wiki/Development-\u0026-test-settings.py"}],"action":{"name":"View Issue","url":"https://github.com/usnistgov/NEMO/issues/3#issuecomment-358093152"}}}
    
    
    -- 
Michael P. Young                                (574) 631-3268 (office)
Nanofabrication Specialist                      (574) 631-4393 (fax)
Department of Electrical Engineering            (765) 637-3784 (cell)
University of Notre Dame                         mike.young@nd.edu
B-38 Stinson-Remick Hall
Notre Dame, IN 46556-5637

**Comment by dylan-klomparens** [comment]
@saltlakeryan is exactly right. The part of `settings.py` that would refer to this is `SECRET_KEY`. This is documented in the [official Django documentation](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-SECRET_KEY), but it looks like I should clarify that portion of the wiki. Thanks for the comment, @dadhogy
