### ISSUE TITLE
Possible bug in area access page

### ISSUE THREAD

**Issue by dsbarth** [usnistgov/NEMO#32]
It looks like there is a bug in the "New area access record" page, where we can manually create an area access. When choosing the area to create the record for, the options are physical access levels, not areas, and choosing any of them results in failure with this error: "Your request contained an invalid identifier."

I think what is going on is that the function get_accessible_areas_for_user is making a list of physical access levels for the user, not areas. The new_area_access_record function is then treating them as areas. It looks like get_accessible_areas_for_user is used in some places where areas are needed and others where physical access levels are needed.

**Comment by dsbarth** [comment]
Looking at this a bit further, it can actually cause an even bigger problem. If by coincidence the ID of the physical access level matches an area that is not the associated one, it will make the area access event, but it will do so for the wrong area.

**Comment by mrampant-nist** [comment]
great catch, thank you!
on my test instance, I named access levels the same as areas... not smart :-(

**Comment by dsbarth** [comment]
The fix basically works, but if a user has multiple physical access levels to the same area, the area is repeated in the list

**Comment by mrampant-nist** [comment]
good point. I fixed it. thanks again for catching this!
