### ISSUE TITLE
Bug in Tool model methods prevents tool enables for non-staff

### ISSUE THREAD

**Issue by dsbarth** [usnistgov/NEMO#33]
I found that for non-staff users, the enable tool button would not appear, even though the project selection works properly. The only change I found was the addition of the ready_to_use() model method instead of checking the conditions individually. I was able to fix it by adding parentheses after the individual method calls within ready_to_use().

This changed line 557 in models.py from:
return self.operational and not self.required_resource_is_unavailable and not self.delayed_logoff_in_progress and not self.

to:
return self.operational and not self.required_resource_is_unavailable() and not self.delayed_logoff_in_progress() and not self.scheduled_outage_in_progress()

**Comment by mrampant-nist** [comment]
I'll release a new bug fix version ASAP.
