### ISSUE TITLE
Docker with PostgreSQL

### ISSUE THREAD

**Issue by mrdawson** [usnistgov/NEMO#41]
I'm hoping to use PostgreSQL, but it appears that the docker image is not configured for this.

Here is the relevant part of the settings.py file.
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'USER': 'username',
        'NAME': 'databasename',
        'PASSWORD': 'password',
        'TEST': {
            'NAME': 'nemotest',
        },
    },
}
```

When I do any `docker run` commands, like compiling the static files, I get the following error:
`django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'`

It looks like this python package is missing. This error may just be the tip of the iceberg.

Also, maybe someone can advise on weather or not SQLite would be fine for us. 
~1000 users, 200+ reservable items, 150+ interlocks.

**Comment by mrampant-nist** [comment]
We use oracle here at NIST and we have a separate Dockerfile to install the right packages.
I would recommend doing something similar for your use case.

My advice would be to first follow instructions in [Development Setup](https://github.com/usnistgov/NEMO/wiki/Development-Setup), then make things work with postgres locally, and finally change the `Dockerfile` to install the necessary packages/libraries.

You will probably need to install `pg_config` (it's already in the python docker image we use) and `pip install psycopg2`.

So it might be as easy as just adding `pip install psycopg2` in the [Dockerfile](https://github.com/usnistgov/NEMO/blob/master/Dockerfile) and rebuilding it. (not tested)

**Comment by mrampant-nist** [comment]
This is also something we might consider adding in the official image

**Comment by mrampant-nist** [comment]
closing this
