### ISSUE TITLE
Feedback page not recognizing an email has been added.

### ISSUE THREAD

**Issue by KyleJHUAPL** [usnistgov/NEMO#48]
Not sure if anything is missing as far as configuration goes, in order for this to function as expected.
![image](https://user-images.githubusercontent.com/59450521/88306228-78359080-ccd8-11ea-9ab1-9a799cb6e928.png)
After adding in a valid email address, and saving said email address, the Feedback page does not update to allow for the submission of user feedback. 
![image](https://user-images.githubusercontent.com/59450521/88306357-a0bd8a80-ccd8-11ea-894b-76e508218c42.png)
Does anything extra need to be done, in order to have this function as expected? I see that email templates need to be added in, is this a requirement before the page is viewable?

**Comment by mrampant-nist** [comment]
Yes, you also need to provide the feedback email template in customization.
We should probably change the wording to explain that as  well
