### ISSUE TITLE
Multiple syntax errors found in multiple files

### ISSUE THREAD

**Issue by noREAVER** [usnistgov/NEMO#6]
In many files it appears the same error syntax
like this one: f'and some string'
For example here
https://github.com/usnistgov/NEMO/blob/96c254109c0fc4ed5d5732d3543921e195be998a/NEMO/views/tool_control.py#L213
https://github.com/usnistgov/NEMO/blob/96c254109c0fc4ed5d5732d3543921e195be998a/NEMO/views/users.py#L185
and many many more files

**Comment by mrampant-nist** [comment]
if you are referring to the strings starting with "f", it's not an error. 
they are known as f-strings and were introduced with Python 3.6
see [pep-0498](https://www.python.org/dev/peps/pep-0498/)

**Comment by dylan-klomparens** [comment]
@mrampant-nist is correct, Literal String Interpolation was introduced in Python 3.6. This is why NEMO only works with Python 3.6 and higher.
