### ISSUE TITLE
Minor bug in upcoming reservations on landing page

### ISSUE THREAD

**Issue by dsbarth** [usnistgov/NEMO#60]
A user reported this bug, which occurs when a reservation is shortened, but a delayed logout is in effect. While the delayed logout is ongoing, the 'Late for your reservation' notification appears on the landing page. It seems this occurs because the descendant reservation created from the shortened one has an end that is still in the future, so it is picked up in the query for reservations in the landing page.

**Comment by mrampant-nist** [comment]
Thanks, I will look into that
