### ISSUE TITLE
Issues downloading feature manual

### ISSUE THREAD

**Issue by rab340** [usnistgov/NEMO#61]
Hi.  When I try to download the feature manual, it fails and gives me this message: This site can’t be reached. 
 raw.githubusercontent.com refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by mrampant-nist** [comment]
I tried a minute ago and it worked for me.
here is a another link if you are still having issues: https://file.io/3fiM15MVljQQ

**Comment by rab340** [comment]
Thank you.  I tried that link and it worked.
