### ISSUE TITLE
Adding support for external remote_user authentication for Apache Basic Auth

### ISSUE THREAD

**Issue by hopsj** [usnistgov/NEMO#65]
Prototyped ability to authorize using remote-user authentication via Apache webserver Basic authentication.

See also: https://httpd.apache.org/docs/2.4/howto/auth.html
See also: https://stackoverflow.com/questions/18139093/base64-authentication-python

Inspecting authentication.py class 'RemoteUserAuthenticationBackend' , seems to assume kerberos authentication based on the function 'clean_username'.  Was able to get it working with Apache basic authentication by using an alternate implementation of clean_username:

```
def clean_username_http_basic_auth(self, username):
                """
                User names arrive in the form "Basic <username>:<password>" where everything after Basic is encoded base64
                See https://stackoverflow.com/questions/18139093/base64-authentication-python
                This function decodes and extracts just the username.
                """

                #
                if not username.startswith("Basic "):
                        auth_logger.warning(
                                f"Expected username to start with Basic"
                        )
                        return "unknown_user"

                #Strip off the 'Basic' and decode
                username_password_decoded = b64decode( username[6:] ).decode('utf-8')

                parts = username_password_decoded.split(':')

                return parts[0]
```

This prototype works locally, but I'm way out of my expertise area here, so have no idea how kosher this approach is.

**Comment by mrampant-nist** [comment]
Unless I am mistaken, this is the same logic that is already implement in `NginxKerberosAuthorizationHeaderAuthenticationBackend`

Try using that backend `AUTHENTICATION_BACKENDS = ['NEMO.views.authentication.NginxKerberosAuthorizationHeaderAuthenticationBackend']` and see if it works

**Comment by hopsj** [comment]
Indeed 

> Unless I am mistaken, this is the same logic that is already implement in `NginxKerberosAuthorizationHeaderAuthenticationBackend`
> 
> Try using that backend `AUTHENTICATION_BACKENDS = ['NEMO.views.authentication.NginxKerberosAuthorizationHeaderAuthenticationBackend']` and see if it works

Indeed, works a charm.

**Comment by mrampant-nist** [comment]
that backend should probably be renamed at some point since it's not really specific to Nginx authentication
