### ISSUE TITLE
Authenticating against an AD / LDAP server

### ISSUE THREAD

**Issue by djdube1** [usnistgov/NEMO#74]
Usually, apps authenticating against an AD / LDAP server provides a way to specify the ldap query parameters (ldap_host, port, bind_dn, etc), user mapping, etc. Do Nemo allow this kind of authentification? Otherwise, what would a typical AD / LDAP authentification setup look like?

Thanks,

**Comment by mrampant-nist** [comment]
```
LDAP_SERVERS = [
    {
        'url': 'ldap.example.com',
	'domain': 'EXAMPLE',
	'port': 636,
	'use_ssl': True,
	'bind_as_authentication': False,
	'bind_username': 'bind_username',
	'bind_password': 'bind_password',
	'base_dn': 'DC=EXAMPLE,DC=COM',
	'search_username_field': 'sAMAccountName',
	'certificate': 'ldap-ca.pem',
    },
]

```

All the bind related parameters and search parameters are not needed if `bind_as_authentication` is `True` (meaning we are using the username/password provided by the user to bind and if that is successful the user is logged in).

more information can be found after this line: https://github.com/usnistgov/NEMO/blob/7ccada1821ca88254e6f5570aa13014ba1b8fcdd/NEMO/views/authentication.py#L160

**Comment by djdube1** [comment]
This seems to work, at least with the "nanofab/nemo:1.12.0" docker image. I'm having issues with the most recent image ("nanofab/nemo:3.9.2"). I'll create another issue for this.

Thanks for the quick response!
