### ISSUE TITLE
Auth and /static problem with the docker installation (based on the wiki)

### ISSUE THREAD

**Issue by djdube1** [usnistgov/NEMO#75]
I've followed the documentation (from the wiki) for deploying the app using docker. I've managed to have it working with the 1.12.0 but the /static directory wasn't working (correctly configured, but all request to static resources failed with 404).

I've decided to update my config to the lasted image released ("3.9.2"). I can access the login page, but submitting returns a 405 on the post to `/login/?next=/`. I'm authenticating against an LDAP / AD server.

My settings.py is based on the one provided there : https://github.com/usnistgov/NEMO/wiki/Installation-with-Docker.

Also, when attaching to the docker container, I can see multiple errors during auth attempts : 
...
[22/Apr/2021 14:49:59] django.db.backends DEBUG (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'NEMO' AND "django_content_type"."model" = 'news'); args=('NEMO', 'news')                                                                                                                         
[22/Apr/2021 14:49:59] django.template DEBUG Exception while resolving variable 'name' in template 'unknown'.
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'
...

Seems like an issue with the image itself (django templating errors?), but I'm also not sure at all if my settings.py file is valid since the doc sometimes refer to old versions of the app (the docker-compose linked in the doc uses the 1.12.0 version for example).

**Comment by djdube1** [comment]
Forgot to mention the auth error : 

[22/Apr/2021 15:18:18] NEMO.views.authentication WARNING User ****** attempted to authenticate with LDAPAuthenticationBackend, but that username does not exist in the database. The user was denied access.
[22/Apr/2021 15:18:18] django.request WARNING Method Not Allowed (POST): /login/

Tried multiple times starting fresh with different configurations. The user in question was working when I used the 1.12.0 docker image..

**Comment by mrampant-nist** [comment]
when using the docker container, do you have a web server configured to serve static files?

**Comment by mrampant-nist** [comment]
also the variable resolving exception are DEBUG messages. in django templates when we want to use a optional variable, say test.name and test doesn't exists, it will through those types of error.
I would turn off the debug message from django, and keep INFO so that the logs are not cluttered with those messages. 

couple questions:

1. did you create the user with the correct username in NEMO (using createsuperuser)?
2. do you have HTTPS configured in your web server? if not, turn every setting that has "SECURE" in it to False and try again.

**Comment by djdube1** [comment]
> when using the docker container, do you have a web server configured to serve static files?

I don't have any other web server beside the one in the container itself. Isn't the container's web server supposed to provide the static files itself?

> did you create the user with the correct username in NEMO (using createsuperuser)?

I used the same name for the `createsuperuser` user as the ldap account I'm trying to connect to. I've tried using a different `createsuperuser` and signing in with an ldap user and either encountered a "user not in database" or a 405.

I'm using the same ldap config that I used in 1.12.0 with seemed to work previously.

> do you have HTTPS configured in your web server? if not, turn every setting that has "SECURE" in it to False and try again.

I've not configured HTTPS yet. I'm working on the basic deployment setup locally. Disabled SESSION_COOKIE_SECURE, SECURE_SSL_REDIRECT, etc. and I get the same 405.

**Comment by mrampant-nist** [comment]
you need a webserver. NEMO doesn't have one.
you can find some info about setting up Nginx here:
https://github.com/usnistgov/NEMO/wiki/Installation-with-Docker#nginx-reverse-proxy

**Comment by mrampant-nist** [comment]
for nginx, you can use our image: nanofab/nginx:2.6.0

map port 80 to whatever port you want on your host machine.
map the following volumes:
- <path_to_conf>/nginx.conf:/root/nginx/nginx.conf
- <path_to_nemo_conf>/static:/root/nginx/nemo

adapt the previous nginx config to this paths like this:

### Static files

   location = /favicon.ico { alias /root/nginx/nemo/favicon.ico; }
	location /static { alias /root/nginx/nemo; }

**Comment by mrampant-nist** [comment]
Here, please follow this guide I just added. it should make things easier to start:

https://github.com/usnistgov/NEMO/wiki/Docker-Compose-installation

**Comment by djdube1** [comment]
The provided indication fixed the problem. The auth issue was due to an invalid bind configuration. Would be nice to be able to provide the whole "search_filter" and template in the parameters so we can add additional filters (limit to resource group, etc).

**Comment by mrampant-nist** [comment]
thanks, glad it worked. thanks for the suggestion. if you know a bit of python you can always give it a shot and create a PR for the additional filters
