### ISSUE TITLE
psycopg2 not available in "nanofab/nemo" docker image

### ISSUE THREAD

**Issue by djdube1** [usnistgov/NEMO#76]
The documentation recommends PostgreSQL for instances with a lot of concurrent connections but the docker image doesn't include the required python package "psycopg2".

Trying to configure the app with "nanofab/nemo:3.9.2", using the django.db.backends.postgresql_psycopg2 database engine (the engine refered to in the Django documentation) :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 20, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'
```

**Comment by mrampant-nist** [comment]
Hi,
At the moment, database modules/packages are not included in NEMO to prevent unnecessary overloading of the image and potential version conflicts. We feel it is better for everyone to choose the correct database module/version for their specific database server.

If you are using docker-compose, please take a look at an example of how to install extra packages:
https://github.com/usnistgov/NEMO/wiki/Plugin-list#how-to-install-plugins-using-docker
