### ISSUE TITLE
no such column: shop_product.category

### ISSUE THREAD

**Issue by shrikantm1999** [usnistgov/NEMO#79]
Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/shop/product/
3.2.3
OperationalError
no such column: shop_product.category
C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\sqlite3\base.py, line 423, in execute
C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe
3.9.5
['C:\\Users\\Administrator\\PycharmProjects\\Ecommerce\\mysite',  'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',  'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',  'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib',  'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39',  'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages']
Tue, 25 May 2021 09:16:38 +0000

**Comment by mrampant-nist** [comment]
there is no "shop" app in NEMO, so I am not sure what your issue is about but it doesn't look like it has anything to do with this project
