### ISSUE TITLE
Email broadcast feature request

### ISSUE THREAD

**Issue by nsieb** [usnistgov/NEMO#85]
Is it possible to add an option for email broadcast to select all users who are registered (later filterable to all active users)? It seems like this would be a common way to send messages to everyone using our facility.

**Comment by rptmat57** [comment]
Thank you for submitting this.
We will be adding this feature to NEMO with a couple of filters:

- checkboxes corresponding to User Types
- a checkbox to select only active users

**Comment by rptmat57** [comment]
closing this ticket. The feature was added in the latest version (3.13.0) as 2 separate feature. email broadcast and excel export via rest API.
