### ISSUE TITLE
Allow tool reservations only within time slot

### ISSUE THREAD

**Issue by enodev0** [usnistgov/NEMO#87]
Hi,
I was wondering if there's a way to only allow reservations within a set time window each day, say from 8AM to 8PM (different for each tool, slot variable on weekends, etc). 
Thanks

**Comment by rptmat57** [comment]
Hi,
Currently there is no way to do this directly.
However, if you set a tool to have a required area access and that area requires a reservation, for example a PECVD tool requiring prior Cleanroom reservation, then the user will only be able to reserve the PECVD after he creates a reservation for the Cleanroom, which can be set to certain hours of the day, weekends etc. through the use of Physical Access Levels

**Comment by rptmat57** [comment]
another way to do this would be to schedule recurring outages for a tool.
for example, you could create an every weekday outage for the PECVD that starts at 8PM and ends at 8AM the next day.
this will prevent users from reserving the tool during those hours
