### ISSUE TITLE
Users who are "Staff" have access to the "Customization" menu

### ISSUE THREAD

**Issue by rmwhite85** [usnistgov/NEMO#89]
In version 3.12.2, when the "Staff" box is checked in a user's page (in Detailed Administration), the user then has access to the Administration/Customization menu. The "Staff" user can then read/write/change the values on the Customization page.

The feature manual indicates that the Customization page should only be available to Admin users. I have tested this in impersonation mode, and with another user who has been set to "Staff."

Running docker, 3.12.2/NGINX/Postgres on Ubuntu 20.04, hosted on AWS.

**Comment by rptmat57** [comment]
thanks for bringing this up. we will fix this inconsistency in the next release.
we will talk it through and update this post when a decision is made.

**Comment by rptmat57** [comment]
the Customization page will only be accessible to admins starting with next release (3.13.0) to be consistent with the feature manual.

**Comment by rptmat57** [comment]
closing this ticket. the fix is included in the latest release (3.13.0)
