### ISSUE TITLE
Email broadcast bug.

### ISSUE THREAD

**Issue by nsieb** [usnistgov/NEMO#91]
I am trying to send an email broadcast but it is telling me "A generic email format has not been customized for your organization yet. You'll need to create one before you can send email broadcasts from within 4D LABS NEMO. Please visit the customizations page to upload a template.".

However, I can see the preview in the broadcast window and there is a template in the customizations page.  I'm also pretty sure I was able to send an email at the end of September.

**Comment by rptmat57** [comment]
thank you for reporting this bug. 
I was able to reproduce it and will release a new patched version soon
