### ISSUE TITLE
Calendar enhancements

### ISSUE THREAD

**Issue by nsieb** [usnistgov/NEMO#94]
On the calendar, it would be great to colour-code the tools and allow someone to select multiple tools at the same time.  Then, for example, a staff member could see which tools in a room are being used and differentiate them by colour.

**Comment by rptmat57** [comment]
The multiple tool selection is not currently available in NEMO, however some of the requested functionality can be achieved using the "All tools" view and the possibility of setting a specific color for each tool/area (in Detailed Administration -> Tool -> Additional Information: Tool Calendar Color)

**Comment by rptmat57** [comment]
Just to add to this discussion, this was brought up a little while back on the NEMO public forum:
https://groups.google.com/a/list.nist.gov/g/nemo/c/fhzwsSpv0Zw/m/Hh7UE5aJAwAJ

you can find more information there as well as a link to a commit from the Princeton version of NEMO where such feature is implemented.

For now, we think the "All tools" view and already existing color property for tools and areas are sufficient, but if this feature was developed and contributed, with maybe a checkbox in customizations to enable it, this is definitely something we would accept into NEMO.
