### ISSUE TITLE
[Feature request] Have dedicated landing pages for reservations

### ISSUE THREAD

**Issue by jat255** [usnistgov/NEMO#96]
As discussed with Mathieu, we have a desire for users to be able to link directly to a page descriptive of certain information within NEMO. Chief among these are reservations, but otherwise usage events and tools could be useful too.

I'm going to take a look at seeing how hard this would be implement, and try to send a PR if I'm successful.

---

We basically want the information in /event_details/reservation/168/, but nicely formatted as an independent page, with links back to the main app, etc.

**Comment by rptmat57** [comment]
Thank you, I don't see any problems with adding this, especially if it's isolated with another link. I'll run it by NanoFab management and confirm soon.

Implementation-wise, one option would be to add a new URL, and a new page that extend base.html and try to include the other fragment (reservation_details.html) in it. this way any change to the original details page would be propagated.

**Comment by jat255** [comment]
Extending the `reservation_details.html` is a good idea, but I think that might be tricky styling-wise since that's all set up for the modal with modal classes and everything. I got a development environment up and running, and I know *just* enough Django that I think I can get this working.

**Comment by jat255** [comment]
![image](https://user-images.githubusercontent.com/1278301/146278127-39b7d316-1a8e-4c48-b852-98c9259fd02b.png)

Hey, look at that, I did it!

**Comment by rptmat57** [comment]
that looks great!
I'll take a look at the PR soon
