### ISSUE TITLE
''comment'' possibility in Staff charge

### ISSUE THREAD

**Issue by polyclementc** [usnistgov/NEMO#98]
Hello
Is it possible to add a comment line when applying a staff charge in order to define if it is a laboratory work (Analysis...etc) or an Administrative work?
Also, if this comment could be seen in ''view your usage'' or in the consultation ''project billing'' it would be great!

Thank you!

**Comment by rptmat57** [comment]
Thank you for submitting this.
The scope seems to be fairly minimal and this could be a good feature to add.
I'll run it by the NanoFab and circle back when a decision is made

**Comment by rptmat57** [comment]
The feature/enhancement was accepted and will be integrated into 3.14.0 if time permits it, or 3.15.0 otherwise

**Comment by rptmat57** [comment]
this was added in version 3.14.0
