### ISSUE TITLE
UX on deleting tool documents caused confusion

### ISSUE THREAD

**Issue by jat255** [usnistgov/NEMO#99]
Hi Mathieu, 

Feel free to close this if you think it's not an issue, but we ran into some user experience challenges with one of our admin users accidentally deleting a tool while trying to manage the tool documents. As I understand it, they uploaded some tool documents, but ran into some issues uploading more due to some sort of max limit or space limitation (I'm not sure what the actual issue there was, since I don't think there should be a limit).

Anyway, to replace the uploaded documents with links, the user checked the "Delete" checkboxes, and then pressed the "Delete" button in the bottom left:

![image](https://user-images.githubusercontent.com/1278301/146976595-2a2a2d1d-93fe-4a80-b7bc-b80ad5af2943.png)

That delete button is for the tool record itself. It then shows a delete confirmation screen:

![image](https://user-images.githubusercontent.com/1278301/146976709-d0cf77df-14ea-4a5e-b387-041160a43d1d.png)

Which (in this case) was ignored, since in the user's mind, they're thinking "yes, of course I want to delete what I just selected".

This was a little bit of user error, of course, but I think there's an opportunity for improving the UX of that process (although I'm not sure how much is configurable in the detailed admin screen). Perhaps making the checkboxes for the tool documents actual delete buttons, or renaming the "Delete" button to "Delete <tool name>" to make it more clear. Maybe also an explicit instruction to "Click save after checking delete boxes to delete documents" or something to that effect.

Again, feel free to close if you think this isn't an issue. Our user certainly won't make that mistake again ;)

**Comment by rptmat57** [comment]
I could see how this would be confusing.
That's unfortunately built-in django admin functionality and cannot be changed very easily as for as I can see...
